// flow-typed signature: 4d984f6948443d99e2f62c4c7333e570
// flow-typed version: <<STUB>>/expo-localization_v~8.1.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-localization'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-localization' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-localization/build/ExpoLocalization' {
  declare module.exports: any;
}

declare module 'expo-localization/build/ExpoLocalization.web' {
  declare module.exports: any;
}

declare module 'expo-localization/build/Localization' {
  declare module.exports: any;
}

declare module 'expo-localization/build/Localization.types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-localization/build/ExpoLocalization.js' {
  declare module.exports: $Exports<'expo-localization/build/ExpoLocalization'>;
}
declare module 'expo-localization/build/ExpoLocalization.web.js' {
  declare module.exports: $Exports<'expo-localization/build/ExpoLocalization.web'>;
}
declare module 'expo-localization/build/Localization.js' {
  declare module.exports: $Exports<'expo-localization/build/Localization'>;
}
declare module 'expo-localization/build/Localization.types.js' {
  declare module.exports: $Exports<'expo-localization/build/Localization.types'>;
}
