// flow-typed signature: cc10774986af00583fd9b32cac2bbbb8
// flow-typed version: <<STUB>>/expo-random_v~8.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-random'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-random' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-random/build/ExpoRandom' {
  declare module.exports: any;
}

declare module 'expo-random/build/ExpoRandom.web' {
  declare module.exports: any;
}

declare module 'expo-random/build/Random' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-random/build/ExpoRandom.js' {
  declare module.exports: $Exports<'expo-random/build/ExpoRandom'>;
}
declare module 'expo-random/build/ExpoRandom.web.js' {
  declare module.exports: $Exports<'expo-random/build/ExpoRandom.web'>;
}
declare module 'expo-random/build/Random.js' {
  declare module.exports: $Exports<'expo-random/build/Random'>;
}
