// flow-typed signature: fb1eb9b350591fdb35f95b65c98f3612
// flow-typed version: <<STUB>>/expo-secure-store_v~8.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-secure-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-secure-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-secure-store/build/ExpoSecureStore' {
  declare module.exports: any;
}

declare module 'expo-secure-store/build/ExpoSecureStore.web' {
  declare module.exports: any;
}

declare module 'expo-secure-store/build/SecureStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-secure-store/build/ExpoSecureStore.js' {
  declare module.exports: $Exports<'expo-secure-store/build/ExpoSecureStore'>;
}
declare module 'expo-secure-store/build/ExpoSecureStore.web.js' {
  declare module.exports: $Exports<'expo-secure-store/build/ExpoSecureStore.web'>;
}
declare module 'expo-secure-store/build/SecureStore.js' {
  declare module.exports: $Exports<'expo-secure-store/build/SecureStore'>;
}
