// flow-typed signature: 7e0908ec27b7b19f191578968e4bbeb7
// flow-typed version: <<STUB>>/redux-persist-expo-securestore_v^2.0.0/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-expo-securestore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-expo-securestore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-expo-securestore/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-expo-securestore/src/index' {
  declare module.exports: $Exports<'redux-persist-expo-securestore/src'>;
}
declare module 'redux-persist-expo-securestore/src/index.js' {
  declare module.exports: $Exports<'redux-persist-expo-securestore/src'>;
}
