// flow-typed signature: 0039397e1e3fa371c6769acce94ed5bc
// flow-typed version: <<STUB>>/@react-native-community/masked-view_v0.1.5/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/masked-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/masked-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/masked-view/js/MaskedView' {
  declare module.exports: any;
}

declare module '@react-native-community/masked-view/js/MaskedViewTypes' {
  declare module.exports: any;
}

declare module '@react-native-community/masked-view/prettier.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/masked-view/index' {
  declare module.exports: $Exports<'@react-native-community/masked-view'>;
}
declare module '@react-native-community/masked-view/index.js' {
  declare module.exports: $Exports<'@react-native-community/masked-view'>;
}
declare module '@react-native-community/masked-view/js/MaskedView.js' {
  declare module.exports: $Exports<'@react-native-community/masked-view/js/MaskedView'>;
}
declare module '@react-native-community/masked-view/js/MaskedViewTypes.js' {
  declare module.exports: $Exports<'@react-native-community/masked-view/js/MaskedViewTypes'>;
}
declare module '@react-native-community/masked-view/prettier.config.js' {
  declare module.exports: $Exports<'@react-native-community/masked-view/prettier.config'>;
}
